# Generated by Django 4.0 on 2023-07-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_evento_post_usuarios_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='es_directivo',
            new_name='es_colaborador',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='es_jefe',
            new_name='es_superusuario',
        ),
    ]
